#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import TwistStamped
class Follower(Node):

    def __init__(self):
        super().__init__('follower')
        # Subscribe to leader's velocity commands
        self.create_subscription(
            TwistStamped,
            '/leader/cmd_vel',
            self.cmd_callback,
            10
        )
        # Publish directly to follower
        self.pub = self.create_publisher(
            TwistStamped,
            '/follower1/cmd_vel',
            10
        )

    def cmd_callback(self, msg):
        # Immediately forward the received command
        self.pub.publish(msg)

def main(args=None):
    rclpy.init(args=args)
    node = Follower()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
